# Generated by Django 2.1.2 on 2018-11-01 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pasteAsMarkdown', '0002_auto_20181031_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastebin',
            name='path',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
