# Generated by Django 2.1.2 on 2018-11-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteAsMarkdown', '0003_auto_20181101_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastebin',
            name='path',
            field=models.UUIDField(blank=True, unique=True),
        ),
    ]
