# Generated by Django 2.1.2 on 2018-11-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteAsMarkdown', '0004_auto_20181101_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastebin',
            name='path',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
